// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oycierxgoverhzksjduh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95Y2llcnhnb3Zlcmh6a3NqZHVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTExODcsImV4cCI6MjA1OTM2NzE4N30.qTwEKJ-lTRUCaw2f2BpdnFqWz15NYtaoVkJ0PSQxsBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);